# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/DF.ui'
#
# Created: Thu Jun 06 14:39:08 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(525, 287)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 461, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineE_Path = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineE_Path.setReadOnly(True)
        self.lineE_Path.setObjectName(_fromUtf8("lineE_Path"))
        self.horizontalLayout.addWidget(self.lineE_Path)
        self.btn_ReadData = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_ReadData.setObjectName(_fromUtf8("btn_ReadData"))
        self.horizontalLayout.addWidget(self.btn_ReadData)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 178, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.btn_ReadPara = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_ReadPara.setObjectName(_fromUtf8("btn_ReadPara"))
        self.horizontalLayout_2.addWidget(self.btn_ReadPara)
        self.btn_Calc = QtGui.QPushButton(Dialog)
        self.btn_Calc.setGeometry(QtCore.QRect(100, 252, 121, 23))
        self.btn_Calc.setObjectName(_fromUtf8("btn_Calc"))
        self.btn_Cancel = QtGui.QPushButton(Dialog)
        self.btn_Cancel.setGeometry(QtCore.QRect(280, 252, 121, 23))
        self.btn_Cancel.setObjectName(_fromUtf8("btn_Cancel"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 501, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 491, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineE_BlockNum = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineE_BlockNum.setReadOnly(True)
        self.lineE_BlockNum.setObjectName(_fromUtf8("lineE_BlockNum"))
        self.horizontalLayout_3.addWidget(self.lineE_BlockNum)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineE_JointNum = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineE_JointNum.setReadOnly(True)
        self.lineE_JointNum.setObjectName(_fromUtf8("lineE_JointNum"))
        self.horizontalLayout_3.addWidget(self.lineE_JointNum)
        self.btn_Config = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_Config.setObjectName(_fromUtf8("btn_Config"))
        self.horizontalLayout_3.addWidget(self.btn_Config)
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 60, 500, 100))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBox__NumStep = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox__NumStep.setMaximum(999999999)
        self.spinBox__NumStep.setObjectName(_fromUtf8("spinBox__NumStep"))
        self.gridLayout.addWidget(self.spinBox__NumStep, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinBox_Ratio = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.spinBox_Ratio.setDecimals(4)
        self.spinBox_Ratio.setMaximum(1.0)
        self.spinBox_Ratio.setSingleStep(0.0001)
        self.spinBox_Ratio.setProperty("value", 0.0001)
        self.spinBox_Ratio.setObjectName(_fromUtf8("spinBox_Ratio"))
        self.gridLayout.addWidget(self.spinBox_Ratio, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.spinBox_timeInterval = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.spinBox_timeInterval.setSingleStep(0.01)
        self.spinBox_timeInterval.setObjectName(_fromUtf8("spinBox_timeInterval"))
        self.gridLayout.addWidget(self.spinBox_timeInterval, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.spinBox_SOR = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.spinBox_SOR.setMaximum(2.0)
        self.spinBox_SOR.setSingleStep(0.01)
        self.spinBox_SOR.setObjectName(_fromUtf8("spinBox_SOR"))
        self.gridLayout.addWidget(self.spinBox_SOR, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 1, 1, 1)
        self.spinBox_SpringStiffness = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_SpringStiffness.setMaximum(9999999)
        self.spinBox_SpringStiffness.setObjectName(_fromUtf8("spinBox_SpringStiffness"))
        self.gridLayout.addWidget(self.spinBox_SpringStiffness, 2, 1, 1, 1)
        self.doubleSpinBox_IFStatic = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_IFStatic.setDecimals(4)
        self.doubleSpinBox_IFStatic.setMaximum(3.0)
        self.doubleSpinBox_IFStatic.setSingleStep(0.0001)
        self.doubleSpinBox_IFStatic.setProperty("value", 0.0)
        self.doubleSpinBox_IFStatic.setObjectName(_fromUtf8("doubleSpinBox_IFStatic"))
        self.gridLayout.addWidget(self.doubleSpinBox_IFStatic, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Blocks data:", None))
        self.btn_ReadData.setText(_translate("Dialog", "select file", None))
        self.label_2.setText(_translate("Dialog", "Parameters :", None))
        self.btn_ReadPara.setText(_translate("Dialog", "read from file", None))
        self.btn_Calc.setText(_translate("Dialog", "Calculate DF", None))
        self.btn_Cancel.setText(_translate("Dialog", "Cancel", None))
        self.groupBox.setTitle(_translate("Dialog", "Configure DF  parameters", None))
        self.label_3.setText(_translate("Dialog", "Block materials number:", None))
        self.label_4.setText(_translate("Dialog", "Joint materials number:", None))
        self.btn_Config.setText(_translate("Dialog", "Configure", None))
        self.label_5.setText(_translate("Dialog", "Statics / Dynamics (0,1):", None))
        self.label_7.setText(_translate("Dialog", "Max. ratio(.02-.0001):", None))
        self.label_8.setText(_translate("Dialog", "Max. time interval(0 for auto):", None))
        self.label_9.setText(_translate("Dialog", "Spring stiffness: ", None))
        self.label_10.setText(_translate("Dialog", "SOR:", None))
        self.label_6.setText(_translate("Dialog", "Steps:", None))
        self.label_11.setText(_translate("Dialog", "Frame of axes:", None))
        self.label_12.setText(_translate("Dialog", "Right-hand", None))

