# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Projects/QtCreator/DDA_UIs/TunnelBolts.ui'
#
# Created: Fri Aug 16 14:44:13 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(539, 457)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 420, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 330, 501, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 211, 22))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox_startBoltIdx = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_startBoltIdx.setObjectName(_fromUtf8("spinBox_startBoltIdx"))
        self.horizontalLayout_4.addWidget(self.spinBox_startBoltIdx)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(250, 50, 211, 22))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_endBoltIdx = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox_endBoltIdx.setObjectName(_fromUtf8("spinBox_endBoltIdx"))
        self.horizontalLayout_5.addWidget(self.spinBox_endBoltIdx)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 441, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 501, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 20, 436, 118))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.b = QtGui.QLineEdit(self.layoutWidget2)
        self.b.setReadOnly(True)
        self.b.setObjectName(_fromUtf8("b"))
        self.gridLayout.addWidget(self.b, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tunnelNo = QtGui.QLineEdit(self.layoutWidget2)
        self.tunnelNo.setReadOnly(True)
        self.tunnelNo.setObjectName(_fromUtf8("tunnelNo"))
        self.gridLayout.addWidget(self.tunnelNo, 0, 1, 1, 1)
        self.tunnelType = QtGui.QLineEdit(self.layoutWidget2)
        self.tunnelType.setReadOnly(True)
        self.tunnelType.setObjectName(_fromUtf8("tunnelType"))
        self.gridLayout.addWidget(self.tunnelType, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.a = QtGui.QLineEdit(self.layoutWidget2)
        self.a.setReadOnly(True)
        self.a.setObjectName(_fromUtf8("a"))
        self.gridLayout.addWidget(self.a, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.c = QtGui.QLineEdit(self.layoutWidget2)
        self.c.setReadOnly(True)
        self.c.setObjectName(_fromUtf8("c"))
        self.gridLayout.addWidget(self.c, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.centerX = QtGui.QLineEdit(self.layoutWidget2)
        self.centerX.setReadOnly(True)
        self.centerX.setObjectName(_fromUtf8("centerX"))
        self.gridLayout.addWidget(self.centerX, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.centerY = QtGui.QLineEdit(self.layoutWidget2)
        self.centerY.setReadOnly(True)
        self.centerY.setObjectName(_fromUtf8("centerY"))
        self.gridLayout.addWidget(self.centerY, 3, 3, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 190, 501, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 451, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 50, 401, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_12.setPalette(palette)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.widget = QtGui.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(250, 70, 211, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        self.spinBox_boltLength2 = QtGui.QDoubleSpinBox(self.widget)
        self.spinBox_boltLength2.setMaximum(9999.99)
        self.spinBox_boltLength2.setProperty("value", 10.0)
        self.spinBox_boltLength2.setObjectName(_fromUtf8("spinBox_boltLength2"))
        self.horizontalLayout_2.addWidget(self.spinBox_boltLength2)
        self.widget1 = QtGui.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(20, 70, 211, 22))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_13 = QtGui.QLabel(self.widget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout.addWidget(self.label_13)
        self.spinBox_boltLength = QtGui.QDoubleSpinBox(self.widget1)
        self.spinBox_boltLength.setMaximum(9999.99)
        self.spinBox_boltLength.setProperty("value", 12.0)
        self.spinBox_boltLength.setObjectName(_fromUtf8("spinBox_boltLength"))
        self.horizontalLayout.addWidget(self.spinBox_boltLength)
        self.widget2 = QtGui.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(20, 100, 211, 22))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_15 = QtGui.QLabel(self.widget2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_3.addWidget(self.label_15)
        self.spinBox_boltDistance = QtGui.QDoubleSpinBox(self.widget2)
        self.spinBox_boltDistance.setMaximum(9999.99)
        self.spinBox_boltDistance.setProperty("value", 4.0)
        self.spinBox_boltDistance.setObjectName(_fromUtf8("spinBox_boltDistance"))
        self.horizontalLayout_3.addWidget(self.spinBox_boltDistance)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Select bolts", None))
        self.label_3.setText(_translate("Dialog", "Start bolt Index:", None))
        self.label_4.setText(_translate("Dialog", "End bolt Index :", None))
        self.label_10.setText(_translate("Dialog", "Bolt elements between start and end indexes will be saved.", None))
        self.groupBox.setTitle(_translate("Dialog", "Tunnel Information", None))
        self.label_2.setText(_translate("Dialog", "Tunnel Type:", None))
        self.label.setText(_translate("Dialog", "Tunnel No:", None))
        self.label_5.setText(_translate("Dialog", "Half width :", None))
        self.label_6.setText(_translate("Dialog", "Half Height :", None))
        self.label_7.setText(_translate("Dialog", "Arc Radius :", None))
        self.label_8.setText(_translate("Dialog", "Center X:", None))
        self.label_9.setText(_translate("Dialog", "CenterY:", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Configure bolts parameters", None))
        self.label_11.setText(_translate("Dialog", "Different lengths for bolts are used to balance tension and stress.", None))
        self.label_12.setText(_translate("Dialog", "Please don\'t change parameters unless you have the experience.", None))
        self.label_14.setText(_translate("Dialog", "bolt length 2:", None))
        self.label_13.setText(_translate("Dialog", "bolt length 1: ", None))
        self.label_15.setText(_translate("Dialog", "bolt distance :", None))

